-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  agent_name character varying DEFAULT 'Iara'::character varying,
  tone_of_voice character varying DEFAULT 'amigavel'::character varying,
  text_size character varying DEFAULT 'curto'::character varying,
  use_emojis boolean DEFAULT false,
  send_documents boolean DEFAULT false,
  auto_scheduling boolean DEFAULT false,
  qualification_fields jsonb DEFAULT '{"nome": true, "email": true, "segmento": true, "telefone": true, "interesse": true, "motivacao": true, "expectativa": true, "nome_igreja": true, "tipo_evento": true, "volume_mensal": true}'::jsonb,
  business_hours jsonb DEFAULT '{"friday": {"enabled": true, "endTime": "18:00", "startTime": "09:00"}, "monday": {"enabled": true, "endTime": "18:00", "startTime": "09:00"}, "sunday": {"enabled": false, "endTime": "13:00", "startTime": "09:00"}, "tuesday": {"enabled": true, "endTime": "18:00", "startTime": "09:00"}, "saturday": {"enabled": false, "endTime": "13:00", "startTime": "09:00"}, "thursday": {"enabled": true, "endTime": "18:00", "startTime": "09:00"}, "wednesday": {"enabled": true, "endTime": "18:00", "startTime": "09:00"}}'::jsonb,
  outside_hours_message text DEFAULT 'Desculpe, estamos fora do horário de atendimento. Retornaremos em breve!'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  agent_prompt text,
  informacoes_adicionais text,
  perguntas_frequentes text,
  principais_eventos text,
  documentacao_necessaria text,
  localizacao_igreja text,
  informacao_historica text,
  google_maps_link text,
  espacos_disponiveis text,
  info_casamento jsonb DEFAULT '{"lugares": "", "valores": "", "horarios": "", "documentacao": "", "prazo_entrega": ""}'::jsonb,
  exige_sinal boolean DEFAULT false,
  regras_sinal text,
  info_batizados jsonb DEFAULT '{"lugares": "", "valores": "", "horarios": "", "documentacao": "", "prazo_entrega": ""}'::jsonb,
  cursos text,
  sessao_fotos text,
  regras_hospedagem text,
  link_visitacao text,
  guia_turistico text,
  projetos_sociais_empresas text,
  projetos_sociais_comunidade text,
  regras_especificas text,
  hospedagem_disponivel boolean DEFAULT false,
  menu_principal text DEFAULT ''::text,
  agent_gender character varying DEFAULT 'feminino'::character varying,
  greeting_message text DEFAULT ''::text,
  error_message text DEFAULT 'Desculpe, não consegui processar sua solicitação. Por favor, tente novamente ou entre em contato conosco.'::text,
  phone_landline character varying DEFAULT ''::character varying,
  phone_whatsapp character varying DEFAULT ''::character varying,
  email_main character varying DEFAULT ''::character varying,
  email_secretary character varying DEFAULT ''::character varying,
  email_documents character varying DEFAULT ''::character varying,
  contact_general text DEFAULT ''::text,
  allow_scheduling_lent boolean DEFAULT true,
  allow_scheduling_jubilee boolean DEFAULT true,
  blocked_dates jsonb DEFAULT '[]'::jsonb,
  max_simultaneous_events integer DEFAULT 1,
  donation_text text DEFAULT ''::text,
  prayer_text text DEFAULT ''::text,
  confirmation_text text DEFAULT 'Seu agendamento foi confirmado com sucesso! Em breve você receberá mais informações.'::text,
  unavailability_text text DEFAULT 'Infelizmente não temos horários disponíveis para a data solicitada. Por favor, escolha outra data ou entre em contato conosco.'::text,
  post_scheduling_text text DEFAULT ''::text,
  imagens_batismos jsonb DEFAULT '[]'::jsonb,
  imagens_casamentos jsonb DEFAULT '[]'::jsonb,
  imagens_espacos jsonb DEFAULT '[]'::jsonb,
  imagens_igreja jsonb DEFAULT '[]'::jsonb,
  imagens_acomodacoes text,
  CONSTRAINT ai_configs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_configs_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.ai_prompts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  prompt_type character varying DEFAULT 'system'::character varying,
  content text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_prompts_pkey PRIMARY KEY (id),
  CONSTRAINT ai_prompts_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT ai_prompts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.arquivos_ia (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  nome character varying NOT NULL,
  nome_original character varying,
  categoria character varying,
  subcategoria character varying,
  descricao text,
  status character varying DEFAULT 'ativo'::character varying,
  disponivel_ia boolean DEFAULT true,
  processado_ia boolean DEFAULT false,
  instrucoes_ia text,
  contexto_uso text,
  palavras_chave ARRAY,
  prioridade integer DEFAULT 0,
  url text,
  bucket_name character varying,
  caminho_storage text,
  tipo_mime character varying,
  extensao character varying,
  tamanho bigint,
  visibilidade character varying DEFAULT 'privado'::character varying,
  versao integer DEFAULT 1,
  visualizacoes integer DEFAULT 0,
  downloads integer DEFAULT 0,
  ultima_utilizacao_ia timestamp with time zone,
  cliente_id uuid,
  produto_id uuid,
  proposta_id uuid,
  contrato_id uuid,
  arquivo_pai_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT arquivos_ia_pkey PRIMARY KEY (id),
  CONSTRAINT arquivos_ia_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT arquivos_ia_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clients(id),
  CONSTRAINT arquivos_ia_arquivo_pai_id_fkey FOREIGN KEY (arquivo_pai_id) REFERENCES public.arquivos_ia(id)
);
CREATE TABLE public.calendar_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  event_type character varying DEFAULT 'meeting'::character varying,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone NOT NULL,
  all_day boolean DEFAULT false,
  location character varying,
  attendees ARRAY,
  reminder_minutes integer DEFAULT 30,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cliente_id uuid,
  color text,
  reminders text,
  notes text,
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_events_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT calendar_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT calendar_events_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clients(id)
);
CREATE TABLE public.church_accommodations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  nome character varying NOT NULL,
  codigo character varying,
  tipo character varying NOT NULL DEFAULT 'individual'::character varying,
  capacidade_maxima integer NOT NULL DEFAULT 1,
  quantidade_disponivel integer NOT NULL DEFAULT 1,
  descricao text,
  possui_banheiro boolean DEFAULT false,
  possui_banheiro_privativo boolean DEFAULT false,
  possui_roupa_cama boolean DEFAULT true,
  possui_toalhas boolean DEFAULT false,
  possui_ar_condicionado boolean DEFAULT false,
  possui_ventilador boolean DEFAULT false,
  possui_tv boolean DEFAULT false,
  possui_wifi boolean DEFAULT true,
  possui_frigobar boolean DEFAULT false,
  comodidades_extras jsonb DEFAULT '[]'::jsonb,
  valor_noite_override numeric,
  fotos jsonb DEFAULT '[]'::jsonb,
  ativo boolean DEFAULT true,
  em_manutencao boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT church_accommodations_pkey PRIMARY KEY (id),
  CONSTRAINT church_accommodations_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.church_hosting_config (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL UNIQUE,
  hospedagem_ativa boolean DEFAULT false,
  descricao text,
  publico_permitido jsonb DEFAULT '["romeiros", "retiros", "eventos"]'::jsonb,
  idade_minima integer DEFAULT 0,
  permite_criancas boolean DEFAULT true,
  permite_animais boolean DEFAULT false,
  acessibilidade text,
  dias_funcionamento jsonb DEFAULT '["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]'::jsonb,
  horario_checkin character varying DEFAULT '14:00'::character varying,
  horario_checkout character varying DEFAULT '12:00'::character varying,
  estadia_minima integer DEFAULT 1,
  estadia_maxima integer DEFAULT 30,
  permite_estender_estadia boolean DEFAULT true,
  datas_bloqueadas jsonb DEFAULT '[]'::jsonb,
  bloqueio_por_evento boolean DEFAULT true,
  valor_por_noite numeric,
  valor_por_pessoa boolean DEFAULT false,
  taxa_limpeza numeric,
  exige_sinal boolean DEFAULT false,
  valor_sinal numeric,
  percentual_sinal integer,
  prazo_pagamento_sinal integer,
  politica_cancelamento text,
  formas_pagamento jsonb DEFAULT '["pix", "dinheiro", "transferencia"]'::jsonb,
  dados_obrigatorios jsonb DEFAULT '["nome", "cpf", "telefone", "email"]'::jsonb,
  exige_documento boolean DEFAULT true,
  tipos_documento jsonb DEFAULT '["rg", "cnh", "passaporte"]'::jsonb,
  ficha_hospede_link text,
  envio_documentos_por jsonb DEFAULT '["upload", "email"]'::jsonb,
  ia_nivel_automacao character varying DEFAULT 'informar'::character varying,
  usa_agendamento_ia boolean DEFAULT false,
  precisa_confirmacao_humana boolean DEFAULT true,
  mensagem_confirmacao_reserva text,
  mensagem_indisponibilidade text,
  regras_hospedagem text,
  termos_responsabilidade text,
  orientacoes_hospede text,
  politica_silencio text,
  informacoes_gerais text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT church_hosting_config_pkey PRIMARY KEY (id),
  CONSTRAINT church_hosting_config_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.church_services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  nome character varying NOT NULL,
  slug character varying NOT NULL,
  tipo character varying NOT NULL DEFAULT 'cerimonia'::character varying,
  ativo boolean DEFAULT true,
  ordem integer DEFAULT 0,
  descricao_curta text,
  descricao_completa text,
  icone character varying,
  etapas jsonb DEFAULT '[]'::jsonb,
  dias_permitidos jsonb DEFAULT '["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]'::jsonb,
  horarios_permitidos jsonb DEFAULT '[]'::jsonb,
  documentos_exigidos jsonb DEFAULT '[]'::jsonb,
  valor numeric,
  valor_variavel boolean DEFAULT false,
  valor_minimo numeric,
  valor_maximo numeric,
  forma_pagamento jsonb DEFAULT '["pix", "dinheiro", "transferencia"]'::jsonb,
  exige_sinal boolean DEFAULT false,
  valor_sinal numeric,
  percentual_sinal integer,
  prazo_pagamento_sinal integer,
  regras text,
  restricoes text,
  prazo_minimo_agendamento integer DEFAULT 30,
  prazo_maximo_agendamento integer DEFAULT 365,
  duracao_media_minutos integer,
  capacidade_maxima integer,
  usa_agendamento boolean DEFAULT false,
  usa_tool_verificar_agendamento boolean DEFAULT false,
  usa_tool_realizar_agendamento boolean DEFAULT false,
  precisa_confirmacao_humana boolean DEFAULT true,
  mensagem_confirmacao text,
  mensagem_indisponibilidade text,
  mensagem_pos_agendamento text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT church_services_pkey PRIMARY KEY (id),
  CONSTRAINT church_services_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.churches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  cnpj character varying,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  state character varying,
  zip_code character varying,
  logo_url text,
  website character varying,
  description text,
  timezone character varying DEFAULT 'America/Sao_Paulo'::character varying,
  language character varying DEFAULT 'pt-BR'::character varying,
  plan character varying DEFAULT 'free'::character varying,
  plan_expires_at timestamp with time zone,
  instance character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  instance_connected_at timestamp with time zone,
  role text,
  instagram character varying,
  facebook character varying,
  tokens_count text,
  total_tokens text,
  CONSTRAINT churches_pkey PRIMARY KEY (id),
  CONSTRAINT churches_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  name character varying NOT NULL,
  email character varying,
  phone character varying,
  whatsapp character varying,
  remote_jid character varying,
  status character varying DEFAULT 'lead'::character varying,
  category character varying DEFAULT 'sem-categoria'::character varying,
  tags ARRAY DEFAULT '{}'::text[],
  notes text,
  address text,
  city character varying,
  state character varying,
  zip_code character varying,
  interest character varying,
  motivation text,
  expectation text,
  event_type character varying,
  source character varying,
  source_details text,
  assigned_to uuid,
  last_contact_at timestamp with time zone,
  next_followup_at timestamp with time zone,
  converted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ultima_mensagem timestamp with time zone,
  origem character varying,
  instancia character varying,
  ultima_conversa text,
  atendimento_ia text,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT clients_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  client_id uuid,
  whatsapp_instance_id uuid,
  remote_jid character varying NOT NULL,
  contact_name character varying,
  status character varying DEFAULT 'active'::character varying,
  last_message_at timestamp with time zone,
  last_message_preview text,
  unread_count integer DEFAULT 0,
  assigned_to uuid,
  tags ARRAY DEFAULT '{}'::text[],
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT conversations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT conversations_whatsapp_instance_id_fkey FOREIGN KEY (whatsapp_instance_id) REFERENCES public.whatsapp_instances(id),
  CONSTRAINT conversations_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  name character varying NOT NULL,
  file_type character varying,
  file_size bigint,
  storage_path text NOT NULL,
  public_url text,
  mime_type character varying,
  related_to_type character varying,
  related_to_id uuid,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT files_pkey PRIMARY KEY (id),
  CONSTRAINT files_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.hosting_reservations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  accommodation_id uuid,
  client_id uuid,
  data_checkin date NOT NULL,
  data_checkout date NOT NULL,
  hospede_nome character varying NOT NULL,
  hospede_cpf character varying,
  hospede_rg character varying,
  hospede_telefone character varying,
  hospede_email character varying,
  hospede_endereco text,
  hospede_data_nascimento date,
  quantidade_hospedes integer DEFAULT 1,
  acompanhantes jsonb DEFAULT '[]'::jsonb,
  valor_total numeric,
  valor_sinal_pago numeric,
  valor_restante numeric,
  status character varying DEFAULT 'pendente'::character varying,
  pagamento_status character varying DEFAULT 'pendente'::character varying,
  forma_pagamento character varying,
  observacoes text,
  motivo_visita text,
  origem character varying DEFAULT 'manual'::character varying,
  atendido_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hosting_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT hosting_reservations_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT hosting_reservations_accommodation_id_fkey FOREIGN KEY (accommodation_id) REFERENCES public.church_accommodations(id),
  CONSTRAINT hosting_reservations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT hosting_reservations_atendido_por_fkey FOREIGN KEY (atendido_por) REFERENCES auth.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  message_id character varying,
  remote_jid character varying NOT NULL,
  direction character varying NOT NULL,
  content_type character varying DEFAULT 'text'::character varying,
  content text,
  media_url text,
  media_mime_type character varying,
  status character varying DEFAULT 'sent'::character varying,
  timestamp timestamp with time zone NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.notices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'info'::character varying,
  priority character varying DEFAULT 'normal'::character varying,
  target_audience character varying DEFAULT 'all'::character varying,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notices_pkey PRIMARY KEY (id),
  CONSTRAINT notices_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT notices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.service_appointments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  service_id uuid NOT NULL,
  client_id uuid,
  data_agendamento date NOT NULL,
  hora_inicio time without time zone,
  hora_fim time without time zone,
  solicitante_nome character varying NOT NULL,
  solicitante_telefone character varying,
  solicitante_email character varying,
  solicitante_cpf character varying,
  detalhes jsonb DEFAULT '{}'::jsonb,
  documentos_entregues jsonb DEFAULT '[]'::jsonb,
  documentos_pendentes jsonb DEFAULT '[]'::jsonb,
  valor_total numeric,
  valor_sinal_pago numeric,
  valor_restante numeric,
  status character varying DEFAULT 'solicitado'::character varying,
  pagamento_status character varying DEFAULT 'pendente'::character varying,
  forma_pagamento character varying,
  observacoes text,
  origem character varying DEFAULT 'manual'::character varying,
  atendido_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT service_appointments_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT service_appointments_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.church_services(id),
  CONSTRAINT service_appointments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT service_appointments_atendido_por_fkey FOREIGN KEY (atendido_por) REFERENCES auth.users(id)
);
CREATE TABLE public.support_ticket_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  nome character varying NOT NULL,
  descricao text,
  cor character varying DEFAULT '#8B5CF6'::character varying,
  icone character varying,
  ativo boolean DEFAULT true,
  ordem integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_ticket_categories_pkey PRIMARY KEY (id),
  CONSTRAINT support_ticket_categories_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.support_ticket_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  church_id uuid NOT NULL,
  tipo character varying NOT NULL,
  conteudo text NOT NULL,
  autor_id uuid,
  autor_nome character varying,
  autor_tipo character varying DEFAULT 'atendente'::character varying,
  whatsapp_message_id character varying,
  whatsapp_status character varying,
  anexos jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_ticket_messages_pkey PRIMARY KEY (id),
  CONSTRAINT support_ticket_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT support_ticket_messages_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT support_ticket_messages_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.support_ticket_reasons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  nome character varying NOT NULL,
  descricao text,
  categoria_id uuid,
  prioridade_padrao character varying DEFAULT 'normal'::character varying,
  ativo boolean DEFAULT true,
  ordem integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_ticket_reasons_pkey PRIMARY KEY (id),
  CONSTRAINT support_ticket_reasons_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT support_ticket_reasons_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.support_ticket_categories(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  nome character varying NOT NULL,
  telefone character varying NOT NULL,
  email character varying,
  motivo character varying NOT NULL,
  categoria character varying,
  assunto character varying,
  observacao text,
  prioridade character varying DEFAULT 'normal'::character varying,
  status character varying DEFAULT 'pendente'::character varying,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  data_resolucao timestamp with time zone,
  responsavel_id uuid,
  responsavel_nome character varying,
  origem character varying DEFAULT 'manual'::character varying,
  conversa_id uuid,
  tags ARRAY,
  anexos jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT support_tickets_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  auth_id uuid NOT NULL UNIQUE,
  church_id uuid NOT NULL,
  name character varying NOT NULL,
  email character varying NOT NULL,
  role character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id),
  CONSTRAINT users_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.visitation_followup_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  response_id uuid NOT NULL,
  church_id uuid NOT NULL,
  tipo character varying NOT NULL,
  descricao text NOT NULL,
  resultado character varying,
  responsavel_id uuid,
  responsavel_nome character varying,
  data_contato timestamp with time zone DEFAULT now(),
  proxima_acao text,
  data_proxima_acao date,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visitation_followup_history_pkey PRIMARY KEY (id),
  CONSTRAINT visitation_followup_history_response_id_fkey FOREIGN KEY (response_id) REFERENCES public.visitation_form_responses(id),
  CONSTRAINT visitation_followup_history_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT visitation_followup_history_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES auth.users(id)
);
CREATE TABLE public.visitation_form_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL UNIQUE,
  titulo character varying NOT NULL DEFAULT 'Formulário de Visitação'::character varying,
  descricao text,
  ativo boolean DEFAULT true,
  cor_primaria character varying DEFAULT '#8B5CF6'::character varying,
  logo_url text,
  mensagem_boas_vindas text,
  mensagem_agradecimento text DEFAULT 'Obrigado por preencher o formulário! Em breve entraremos em contato.'::text,
  campos_config jsonb DEFAULT '{"cep": {"ativo": false, "label": "CEP", "obrigatorio": false}, "nome": {"ativo": true, "label": "Nome completo", "obrigatorio": true}, "email": {"ativo": true, "label": "E-mail", "obrigatorio": false}, "bairro": {"ativo": false, "label": "Bairro", "obrigatorio": false}, "cidade": {"ativo": false, "label": "Cidade", "obrigatorio": false}, "estado": {"ativo": false, "label": "Estado", "obrigatorio": false}, "endereco": {"ativo": false, "label": "Endereço", "obrigatorio": false}, "telefone": {"ativo": true, "label": "Telefone/WhatsApp", "obrigatorio": true}, "observacoes": {"ativo": false, "label": "Observações", "obrigatorio": false}, "qual_igreja": {"ativo": false, "label": "Qual igreja?", "obrigatorio": false}, "como_conheceu": {"ativo": true, "label": "Como conheceu nossa igreja?", "obrigatorio": false}, "motivo_visita": {"ativo": true, "label": "Motivo da visita", "obrigatorio": false}, "pedido_oracao": {"ativo": true, "label": "Pedido de oração", "obrigatorio": false}, "data_nascimento": {"ativo": false, "label": "Data de nascimento", "obrigatorio": false}, "ja_frequenta_igreja": {"ativo": false, "label": "Já frequenta alguma igreja?", "obrigatorio": false}, "deseja_receber_visita": {"ativo": true, "label": "Deseja receber visita?", "obrigatorio": false}, "melhor_horario_contato": {"ativo": false, "label": "Melhor horário para contato", "obrigatorio": false}}'::jsonb,
  campos_personalizados jsonb DEFAULT '[]'::jsonb,
  opcoes_como_conheceu jsonb DEFAULT '["Indicação de amigo/familiar", "Redes sociais", "Passou em frente", "Evento", "Busca na internet", "Outro"]'::jsonb,
  opcoes_motivo_visita jsonb DEFAULT '["Primeira visita", "Conhecer a igreja", "Buscar orientação espiritual", "Participar de evento", "Acompanhar familiar/amigo", "Outro"]'::jsonb,
  notificar_email boolean DEFAULT true,
  emails_notificacao ARRAY,
  notificar_whatsapp boolean DEFAULT false,
  slug character varying UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visitation_form_config_pkey PRIMARY KEY (id),
  CONSTRAINT visitation_form_config_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.visitation_form_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  form_config_id uuid NOT NULL,
  nome character varying NOT NULL,
  email character varying,
  telefone character varying,
  data_nascimento date,
  endereco text,
  bairro character varying,
  cidade character varying,
  estado character varying,
  cep character varying,
  como_conheceu character varying,
  motivo_visita character varying,
  pedido_oracao text,
  ja_frequenta_igreja boolean,
  qual_igreja character varying,
  deseja_receber_visita boolean,
  melhor_horario_contato character varying,
  observacoes text,
  campos_personalizados_respostas jsonb DEFAULT '{}'::jsonb,
  data_visita date DEFAULT CURRENT_DATE,
  ip_address character varying,
  user_agent text,
  status character varying DEFAULT 'novo'::character varying,
  notas_acompanhamento text,
  responsavel_acompanhamento uuid,
  data_ultimo_contato timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visitation_form_responses_pkey PRIMARY KEY (id),
  CONSTRAINT visitation_form_responses_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT visitation_form_responses_form_config_id_fkey FOREIGN KEY (form_config_id) REFERENCES public.visitation_form_config(id),
  CONSTRAINT visitation_form_responses_responsavel_acompanhamento_fkey FOREIGN KEY (responsavel_acompanhamento) REFERENCES auth.users(id)
);
CREATE TABLE public.whatsapp_chats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  instance_name character varying NOT NULL,
  remote_jid character varying NOT NULL,
  contact_name character varying,
  contact_push_name character varying,
  profile_picture_url text,
  is_group boolean DEFAULT false,
  unread_count integer DEFAULT 0,
  last_message_at timestamp with time zone,
  last_message_preview text,
  is_archived boolean DEFAULT false,
  is_pinned boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_chats_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_chats_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.whatsapp_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  instance_name character varying NOT NULL,
  jid character varying NOT NULL,
  phone_number character varying,
  name character varying,
  push_name character varying,
  profile_picture_url text,
  profile_status text,
  is_business boolean DEFAULT false,
  is_blocked boolean DEFAULT false,
  last_seen timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_contacts_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.whatsapp_instances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  instance_name character varying NOT NULL UNIQUE,
  instance_id character varying,
  phone_number character varying,
  status character varying DEFAULT 'disconnected'::character varying,
  qr_code text,
  connected_at timestamp with time zone,
  disconnected_at timestamp with time zone,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT whatsapp_instances_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_instances_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id)
);
CREATE TABLE public.whatsapp_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  message_id uuid,
  media_key character varying,
  media_type character varying NOT NULL,
  mimetype character varying,
  filename character varying,
  file_size integer,
  duration integer,
  width integer,
  height integer,
  url text,
  storage_path text,
  base64_data text,
  thumbnail_base64 text,
  is_downloaded boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_media_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_media_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT whatsapp_media_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.whatsapp_messages(id)
);
CREATE TABLE public.whatsapp_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  chat_id uuid NOT NULL,
  instance_name character varying NOT NULL,
  message_id character varying NOT NULL,
  remote_jid character varying NOT NULL,
  from_me boolean NOT NULL,
  sender_jid character varying,
  sender_name character varying,
  message_type character varying NOT NULL,
  text_content text,
  caption text,
  media_url text,
  media_mimetype character varying,
  media_filename character varying,
  media_size integer,
  media_duration integer,
  media_base64 text,
  thumbnail_base64 text,
  latitude numeric,
  longitude numeric,
  location_name character varying,
  location_address text,
  vcard text,
  status character varying DEFAULT 'sent'::character varying,
  is_edited boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  is_forwarded boolean DEFAULT false,
  quoted_message_id character varying,
  quoted_message_preview text,
  reaction_emoji character varying,
  reaction_to_message_id character varying,
  message_timestamp timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_messages_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_messages_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT whatsapp_messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.whatsapp_chats(id)
);